---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  db_root_password: cGFzc3dvcmQ=
  git_repo_link: aHR0cHM6Ly9naXRodWIuY29tL01hbm9qRGhhbm9ya2FyL2t1YmVybmV0ZXMtZmxhc2stbXlzcWw=